name: Deploy Static Web App via Marketplace

on:
  push:
    branches:
      - main

jobs:
  deploy-static-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure and Upload
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name nihanthstorageaccount --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}" --source ./Baristahtml --destination '$web' --overwrite true
